import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService with ChangeNotifier {
  String _currentLanguage = 'English';

  String get currentLanguage => _currentLanguage;

  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'settings': 'Settings',
      'preferences': 'Preferences',
      'push_notifications': 'Push Notifications',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'account': 'Account',
      'change_password': 'Change Password',
      'privacy_policy': 'Privacy Policy',
      'danger_zone': 'Danger Zone',
      'delete_account': 'Delete Account',
      'logout': 'Logout',
      'home': 'Home',
      'appointments': 'Appointments',
      'profile': 'Profile',
      'search': 'Search',
      'book': 'Book',
      'select_language': 'Select Language',
      'cancel': 'Cancel',
      'ok': 'OK',
      'changed_to': 'changed to',
      'syncing_profile': 'Syncing profile...',
      'welcome_back': 'Welcome Back',
      'faculty_member': 'Faculty Member',
      'student_member': 'Student',
      'faculty_subtitle': 'Review and manage your pending appointments',
      'student_subtitle': 'Manage your faculty appointments efficiently',
      'quick_actions': 'Quick Actions',
      'book_appointment': 'Book Appointment',
      'faculty_list': 'Faculty List',
      'recent_requests': 'Recent Requests',
      'upcoming_appointments': 'Upcoming Appointments',
      'view_all': 'View All',
      'no_appointments': 'No appointments found',
      'select_faculty': 'Select Faculty',
      'choose_professor': 'Choose a professor',
      'select_date': 'Select Date',
      'choose_date': 'Choose a date',
      'available_time_slots': 'Available Time Slots',
      'reason_for_appointment': 'Reason for Appointment',
      'purpose_hint': 'Briefly describe your purpose',
      'confirm_booking': 'Confirm Booking',
      'booking_success': 'Appointment Requested Successfully!',
      'please_complete_all_fields': 'Please complete all fields',
      'no_available_dates': 'No available dates found',
      'not_accepting_appointments': 'Not accepting appointments currently',
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'department': 'Department',
      'id_number': 'ID Number',
      'phone_number': 'Phone Number',
      'year_of_study': 'Year of Study',
      'save': 'Save',
      'profile_updated': 'Profile updated successfully!',
      'office_hours': 'Office Hours',
      'working_days': 'Working Days',
      'time_range': 'Time Range',
      'to': 'TO',
      'total': 'Total',
      'completed': 'Completed',
      'academic_details': 'Academic Details',
      'email_address': 'Email Address',
      'security': 'Security',
      'password_privacy': 'Password & Privacy',
      'manage_appointment': 'Manage Appointment',
      'approve_reject_question': 'Do you want to approve or reject this appointment request?',
      'rejection_reason': 'Rejection Reason',
      'provide_rejection_reason': 'Please provide a reason for rejection:',
      'confirm_reject': 'Confirm Reject',
      'please_select_faculty': 'Please select a faculty',
      'please_select_reason': 'Please enter a reason',
      'error_loading_list': 'Error loading faculty list',
      'retry': 'Retry',
      'no_faculty_found': 'No faculty members found',
      'refresh': 'Refresh',
      'user': 'User',
      'pending': 'Pending',
      'approved': 'Approved',
      'confirmed': 'Confirmed',
      'rejected': 'Rejected',
      'faculty_note': 'Faculty Note',
      'student': 'Student',
      'faculty': 'Faculty',
      'for_research_paper_purpose': 'For research Paper purpose',
      'for_research_paper_discussion': 'For research paper discussion',
      'for_practical_submission': 'For Practical Submission',
      'not_possible_on_that_day': 'Not possible on that day',
      'meeting': 'Meeting',
      'for_project_discussion': 'For project discussion',
      'exam_query': 'Exam query',
      'personal_reason': 'Personal reason',
      'urgent_work': 'Urgent work',
      'computer_engineering': 'Computer Engineering',
      'information_technology': 'Information Technology',
      'civil_engineering': 'Civil Engineering',
      'mechanical_engineering': 'Mechanical Engineering',
      'electrical_engineering': 'Electrical Engineering',
      'ce': 'CE',
      'it': 'IT',
      'civil': 'Civil',
      'me': 'ME',
      'ee': 'EE',
      'Sagar Patel': 'Sagar Patel',
      'Bhadaliya Manthan': 'Bhadaliya Manthan',
      'english': 'English',
      'hindi': 'हिंदी',
      'gujarati': 'ગુજરાતી',
      'spanish': 'Español',
      'french': 'Français',
    },
    'Hindi': {
      'settings': 'सेटिंग्स',
      'preferences': 'प्राथमिकताएं',
      'push_notifications': 'पुश नोटिफिकेशन',
      'dark_mode': 'डार्क मोड',
      'language': 'भाषा',
      'account': 'खाता',
      'change_password': 'पासवर्ड बदलें',
      'privacy_policy': 'गोपनीयता नीति',
      'danger_zone': 'खतरनाक क्षेत्र',
      'delete_account': 'खाता हटाएं',
      'logout': 'लॉगआउट',
      'home': 'होम',
      'appointments': 'नियुक्ति',
      'profile': 'प्रोफ़ाइल',
      'search': 'खोजें',
      'book': 'बुक करें',
      'select_language': 'भाषा चुनें',
      'cancel': 'रદ્દ करें',
      'ok': 'ठीक है',
      'changed_to': 'में बदल दिया गया',
      'syncing_profile': 'प्रोफ़ाइल सिंक हो रही है...',
      'welcome_back': 'वापसी पर स्वागत है',
      'faculty_member': 'संकाय सदस्य',
      'student_member': 'छात्र',
      'faculty_subtitle': 'अपनी लंबित नियुक्तियों की समीक्षा और प्रबंधन करें',
      'student_subtitle': 'अपनी संकाय नियुक्तियों को कुशलतापूर्वक प्रबंधित करें',
      'quick_actions': 'त्वरित कार्रवाइयां',
      'book_appointment': 'नियुक्ति बुक करें',
      'faculty_list': 'संकाय सूची',
      'recent_requests': 'हाल के अनुरोध',
      'upcoming_appointments': 'आगामी नियुक्तियां',
      'view_all': 'सभी देखें',
      'no_appointments': 'कोई नियुक्ति नहीं मिली',
      'select_faculty': 'संकाय चुनें',
      'choose_professor': 'एक प्रोफेसर चुनें',
      'select_date': 'तारीख चुनें',
      'choose_date': 'एक तारीख चुनें',
      'available_time_slots': 'उपलब्ध समय स्लॉट',
      'reason_for_appointment': 'नियुक्ति का कारण',
      'purpose_hint': 'अपने उद्देश्य का संक्षेप में वर्णन करें',
      'confirm_booking': 'बुकिंग की पुष्टि करें',
      'booking_success': 'नियुक्ति का सफलतापूर्वक अनुरोध किया गया!',
      'please_complete_all_fields': 'कृपया सभी फ़ील्ड भरें',
      'no_available_dates': 'कोई उपलब्ध तारीख नहीं मिली',
      'not_accepting_appointments': 'वर्तमान में नियुक्तियां स्वीकार नहीं कर रहे हैं',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'full_name': 'पूरा नाम',
      'department': 'विभाग',
      'id_number': 'आईडी नंबर',
      'phone_number': 'फ़ोन नंबर',
      'year_of_study': 'अध्ययन का वर्ष',
      'save': 'सहेजें',
      'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
      'office_hours': 'कार्यालय समय',
      'working_days': 'कार्य दिवस',
      'time_range': 'समय सीमा',
      'to': 'सेवा में',
      'total': 'कुल',
      'completed': 'पूरा हुआ',
      'academic_details': 'शैक्षणिक विवरण',
      'email_address': 'ईमेल पता',
      'security': 'सुरक्षा',
      'password_privacy': 'पासवर्ड और गोपनीयता',
      'manage_appointment': 'नियुक्ति प्रबंधित करें',
      'approve_reject_question': 'क्या आप इस नियुक्ति अनुरोध को स्वीकार या अस्वीकार करना चाहते हैं?',
      'rejection_reason': 'अस्वीकृति का कारण',
      'provide_rejection_reason': 'अस्वीकृति के लिए कृपया एक कारण बताएं:',
      'confirm_reject': 'अस्वीकृति की पुष्टि करें',
      'please_select_faculty': 'कृपया एक संकाय चुनें',
      'please_select_reason': 'कृपया एक कारण दर्ज करें',
      'error_loading_list': 'संकाय सूची लोड करने में त्रुटि',
      'retry': 'पुनः प्रयास करें',
      'no_faculty_found': 'कोई संकाय सदस्य नहीं मिला',
      'refresh': 'रीफ्रेश करें',
      'user': 'उपयोगकर्ता',
      'pending': 'लंबित',
      'approved': 'अनुमोदित',
      'confirmed': 'पुष्टि की गई',
      'rejected': 'अस्वीकार कर दिया',
      'faculty_note': 'संकाय नोट',
      'student': 'छात्र',
      'faculty': 'संकाय',
      'for_research_paper_purpose': 'शोध पत्र के उद्देश्य के लिए',
      'for_research_paper_discussion': 'शोध पत्र चर्चा के लिए',
      'for_practical_submission': 'प्रैक्टिकल सबमिशन के लिए',
      'not_possible_on_that_day': 'उस दिन संभव नहीं है',
      'meeting': 'बैठक',
      'for_project_discussion': 'परियोजना चर्चा के लिए',
      'exam_query': 'परीक्षा संबंधी प्रश्न',
      'personal_reason': 'व्यक्तिगत कारण',
      'urgent_work': 'जरूरी काम',
      'computer_engineering': 'कंप्यूटर इंजीनियरिंग',
      'information_technology': 'सूचना प्रौद्योगिकी',
      'civil_engineering': 'सिविल इंजीनियरिंग',
      'mechanical_engineering': 'मैकेनिकल इंजीनियरिंग',
      'electrical_engineering': 'इलेक्ट्रिकल इंजीनियरिंग',
      'ce': 'सीई',
      'it': 'आईटी',
      'civil': 'सिविल',
      'me': 'एमई',
      'ee': 'ईई',
      'Sagar Patel': 'सागर पटेल',
      'Bhadaliya Manthan': 'भडलिया मंथन',
      'english': 'English',
      'hindi': 'हिंदी',
      'gujarati': 'ગુજરાતી',
      'spanish': 'Español',
      'french': 'Français',
    },
    'Gujarati': {
      'settings': 'સેટિંગ્સ',
      'preferences': 'પસંદગીઓ',
      'push_notifications': 'પુશ નોટિફિકેશન',
      'dark_mode': 'ડાર્ક મોડ',
      'language': 'ભાષા',
      'account': 'ખાતું',
      'change_password': 'પાસવર્ડ બદલો',
      'privacy_policy': 'ગોપનીયતા નીતિ',
      'danger_zone': 'ડેન્જર ઝોન',
      'delete_account': 'ખાતું કાઢી નાખો',
      'logout': 'લોગઆઉટ',
      'home': 'હોમ',
      'appointments': 'મુલાકાતો',
      'profile': 'પ્રોફાઇલ',
      'search': 'શોધો',
      'book': 'બુક કરો',
      'select_language': 'ભાષા પસંદ કરો',
      'cancel': 'રદ કરો',
      'ok': 'બરાબર',
      'changed_to': 'માં બદલાયું',
      'syncing_profile': 'પ્રોફાઇલ સિંક થઈ રહી છે...',
      'welcome_back': 'ફરી સ્વાગત છે',
      'faculty_member': 'ફેકલ્ટી મેમ્બર',
      'student_member': 'વિદ્યાર્થી',
      'faculty_subtitle': 'તમારી બાકી મુલાકાતોની સમીક્ષા અને સંચાલન કરો',
      'student_subtitle': 'તમારી ફેકલ્ટી મુલાકાતોને કાર્યક્ષમ રીતે સંચાલિત કરો',
      'quick_actions': 'ઝડપી કાર્યો',
      'book_appointment': 'મુલાકાત બુક કરો',
      'faculty_list': 'ફેકલ્ટી યાદી',
      'recent_requests': 'તાજેતરની વિનંતીઓ',
      'upcoming_appointments': 'આગામી મુલાકાતો',
      'view_all': 'બધું જુઓ',
      'no_appointments': 'કોઈ મુલાકાતો મળી નથી',
      'select_faculty': 'ફેકલ્ટી પસંદ કરો',
      'choose_professor': 'પ્રોફેસર પસંદ કરો',
      'select_date': 'તારીખ પસંદ કરો',
      'choose_date': 'તારીખ પસંદ કરો',
      'available_time_slots': 'ઉપલબ્ધ સમય સ્લોટ્સ',
      'reason_for_appointment': 'મુલાકાતનું કારણ',
      'purpose_hint': 'તમારા હેતુનું ટૂંકમાં વર્ણન કરો',
      'confirm_booking': 'બુકિંગની પુષ્ટિ કરો',
      'booking_success': 'મુલાકાતની વિનંતી સફળતાપૂર્વક કરવામાં આવી!',
      'please_complete_all_fields': 'કૃપા કરીને બધી વિગતો ભરો',
      'no_available_dates': 'કોઈ ઉપલબ્ધ તારીખો મળી નથી',
      'not_accepting_appointments': 'હાલમાં આ ફેકલ્ટી મુલાકાતો સ્વીકારતા નથી',
      'edit_profile': 'પ્રોફાઇલ સંપાદિત કરો',
      'full_name': 'પૂરું નામ',
      'department': 'વિભાગ',
      'id_number': 'આઈડી નંબર',
      'phone_number': 'ફોન નંબર',
      'year_of_study': 'અભ્યાસનું વર્ષ',
      'save': 'સેવ કરો',
      'profile_updated': 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!',
      'office_hours': 'ઓફિસ સમય',
      'working_days': 'કામના દિવસો',
      'time_range': 'સમય મર્યાદા',
      'to': 'થી',
      'total': 'કુલ',
      'Total': 'કુલ',
      'pending': 'બાકી',
      'Pending': 'બાકી',
      'completed': 'પૂર્ણ',
      'Completed': 'પૂર્ણ',
      'academic_details': 'શૈક્ષણિક વિગતો',
      'Academic Details': 'શૈક્ષણિક વિગતો',
      'year_of_study': 'અભ્યાસનું વર્ષ',
      'Year of Study': 'અભ્યાસનું વર્ષ',
      'email_address': 'ઇમેઇલ સરનામું',
      'Email Address': 'ઇમેઇલ સરનામું',
      'phone_number': 'ફોન નંબર',
      'Phone Number': 'ફોન નંબર',
      'security': 'સુરક્ષા',
      'Security': 'સુરક્ષા',
      'password_privacy': 'પાસવર્ડ અને ગોપનીયતા',
      'Password & Privacy': 'પાસવર્ડ અને ગોપનીયતા',
      'computer_science': 'કમ્પ્યુટર સાયન્સ',
      'Computer Science': 'કમ્પ્યુટર સાયન્સ',
      '1st_year': 'પ્રથમ વર્ષ',
      '2nd_year': 'બીજું વર્ષ',
      '3rd_year': 'ત્રીજું વર્ષ',
      '4th_year': 'ચોથું વર્ષ',
      '1st Year': 'પ્રથમ વર્ષ',
      '2nd Year': 'બીજું વર્ષ',
      '3rd Year': 'ત્રીજું વર્ષ',
      '4th Year': 'ચોથું વર્ષ',
      'manage_appointment': 'મુલાકાત સંચાલિત કરો',
      'approve_reject_question': 'શું તમે આ મુલાકાતની વિનંતીને મંજૂર કે નામંજૂર કરવા માંગો છો?',
      'rejection_reason': 'નામંજૂર કરવાનું કારણ',
      'provide_rejection_reason': 'કૃપા કરીને નામંજૂર કરવાનું કારણ આપો:',
      'confirm_reject': 'નામંજૂરીની પુષ્ટિ કરો',
      'please_select_faculty': 'કૃપા કરીને ફેકલ્ટી પસંદ કરો',
      'please_select_reason': 'કૃપા કરીને કારણ દાખલ કરો',
      'error_loading_list': 'ફેકલ્ટી યાદી લોડ કરવામાં ભૂલ',
      'retry': 'ફરી પ્રયાસ કરો',
      'no_faculty_found': 'કોઈ ફેકલ્ટી સભ્યો મળ્યા નથી',
      'refresh': 'રીફ્રેશ કરો',
      'user': 'વપરાશકર્તા',
      'approved': 'મંજૂર',
      'confirmed': 'પુષ્ટિ કરી',
      'rejected': 'નામંજૂર',
      'faculty_note': 'ફેકલ્ટી નોંધ',
      'student': 'વિદ્યાર્થી',
      'faculty': 'ફેકલ્ટી',
      'for_research_paper_purpose': 'સંશોધન પેપર હેતુ માટે',
      'for_research_paper_discussion': 'સંશોધન પેપર ચર્ચા માટે',
      'for_practical_submission': 'પ્રેક્ટિકલ સબમિશન માટે',
      'not_possible_on_that_day': 'તે દિવસે શક્ય નથી',
      'meeting': 'મુલાકાત',
      'for_project_discussion': 'પ્રોજેક્ટ ચર્ચા માટે',
      'exam_query': 'પરીક્ષા પ્રશ્ન',
      'personal_reason': 'વ્યક્તિગત કારણ',
      'urgent_work': 'તાકીદનું કામ',
      'computer_engineering': 'કમ્પ્યુટર એન્જિનિયરિંગ',
      'information_technology': 'ઇન્ફોર્મેશન ટેકનોલોજી',
      'civil_engineering': 'સિવિલ એન્જિનિયરિંગ',
      'mechanical_engineering': 'મિકેનિકલ એન્જિનિયરિંગ',
      'electrical_engineering': 'ઇલેક્ટ્રિકલ એન્જિનિયરિંગ',
      'ce': 'CE',
      'it': 'IT',
      'civil': 'સિવિલ',
      'me': 'ME',
      'ee': 'EE',
      'Sagar Patel': 'સાગર પટેલ',
      'Bhadaliya Manthan': 'ભાદલિયા મંથન',
      'english': 'English',
      'hindi': 'हिंदी',
      'gujarati': 'ગુજરાતી',
      'spanish': 'Español',
      'french': 'Français',
    },
    'Spanish': {
      'settings': 'Ajustes',
      'preferences': 'Preferencias',
      'push_notifications': 'Notificaciones',
      'dark_mode': 'Modo Oscuro',
      'language': 'Idioma',
      'account': 'Cuenta',
      'change_password': 'Cambiar Contraseña',
      'privacy_policy': 'Privacidad',
      'danger_zone': 'Zona de Peligro',
      'delete_account': 'Eliminar Cuenta',
      'logout': 'Cerrar Sesión',
      'home': 'Inicio',
      'appointments': 'Citas',
      'profile': 'Perfil',
      'search': 'Buscar',
      'book': 'Reservar',
      'select_language': 'Seleccionar Idioma',
      'cancel': 'Cancelar',
      'ok': 'OK',
    },
    'French': {
      'settings': 'Paramètres',
      'preferences': 'Préférences',
      'push_notifications': 'Notifications',
      'dark_mode': 'Mode Sombre',
      'language': 'Langue',
      'account': 'Compte',
      'change_password': 'Changer le mot de passe',
      'privacy_policy': 'Confidentialité',
      'danger_zone': 'Zone de Danger',
      'delete_account': 'Supprimer le compte',
      'logout': 'Déconnexion',
      'home': 'Accueil',
      'appointments': 'Rendez-vous',
      'profile': 'Profil',
      'search': 'Rechercher',
      'book': 'Réserver',
      'select_language': 'Choisir la langue',
      'cancel': 'Annuler',
      'ok': 'OK',
    },
  };

  LanguageService() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('language') ?? 'English';
    notifyListeners();
  }

  Future<void> setLanguage(String language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', language);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? _translations['English']![key] ?? key;
  }

  String tryTranslate(String text) {
    if (text.isEmpty) return text;
    String cleanText = text.trim();
    
    // 1. Try case-sensitive exact match
    if (_translations[_currentLanguage]!.containsKey(cleanText)) {
      return _translations[_currentLanguage]![cleanText]!;
    }
    
    // 2. Try case-insensitive match
    String lower = cleanText.toLowerCase();
    for (var entry in _translations[_currentLanguage]!.entries) {
      if (entry.key.toLowerCase() == lower) {
        return entry.value;
      }
    }
    
    // 3. Try normalized match (spaces as underscores)
    String normalized = lower.replaceAll(RegExp(r'\s+'), '_');
    if (_translations[_currentLanguage]!.containsKey(normalized)) {
      return _translations[_currentLanguage]![normalized]!;
    }
    
    return cleanText;
  }
}
